from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
import appCore

class mainScreen(appCore.windowClass):
    def __init__(self):
        super(appCore.windowClass, self).__init__()
        self.createNode()

    def setupWidget(self):
        #Setups the main window
        self.setWindowTitle('Main Window')
        self.setGeometry(0, 0, 1920, 1080)

        #Setups main window size
        sizePolicy = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(26)
        sizePolicy.setVerticalStretch(24)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)

        #Setups several main widgets
        self.centralwidget = appCore.widgetClass(self)
        self.formLayout = QFormLayout(self.centralwidget)
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = appCore.widgetClass()
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 1920, 1080))

        self.gridLayout = QGridLayout(self.scrollAreaWidgetContents)
        self.frame = appCore.frameClass(self.scrollAreaWidgetContents)
        self.frame.setMaximumSize(QSize(16777215, 1000000))
        self.horizontalLayout = QHBoxLayout(self.frame)
        self.frame.createBtn("learn", "Learn", True)
        self.horizontalLayout.addWidget(self.frame.learn_btn)
        self.frame.createBtn("lorem", "Lorem", True)
        self.horizontalLayout.addWidget(self.frame.lorem_btn)
        self.frame.createBtn("settings", "Settings", True)
        self.horizontalLayout.addWidget(self.frame.settings_btn)
        self.frame.createBtn("node_1", "Logout", True)
        self.horizontalLayout.addWidget(self.frame.node_1_btn)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 2)

        self.widget_2 = appCore.widgetClass(self.scrollAreaWidgetContents)
        self.gridLayout_2 = QGridLayout(self.widget_2)
        self.gridLayout_2.setSizeConstraint(QLayout.SetNoConstraint)
        self.widget_2.createBtn("node_4", "pb1", False)
        self.gridLayout_2.addWidget(self.widget_2.node_4_btn, 1, 2, 1, 1)
        self.widget_2.createBtn("pb2", "pb2", False)
        self.gridLayout_2.addWidget(self.widget_2.pb2_btn, 1, 0, 1, 1)
        self.widget_2.createBtn("pb3", "pb3", False)
        self.gridLayout_2.addWidget(self.widget_2.pb3_btn, 9, 1, 1, 1)
        self.widget_2.createBtn("pb4", "pb4", False)
        self.gridLayout_2.addWidget(self.widget_2.pb4_btn, 14, 1, 1, 1)
        self.widget_2.createBtn("pb5", "pb5", False)
        self.gridLayout_2.addWidget(self.widget_2.pb5_btn, 10, 2, 1, 1)
        self.widget_2.createBtn("pb6", "pb6", False)
        self.gridLayout_2.addWidget(self.widget_2.pb6_btn, 5, 1, 1, 1)
        self.widget_2.createBtn("pb7", "pb7", False)
        self.gridLayout_2.addWidget(self.widget_2.pb7_btn, 0, 1, 1, 1)
        self.widget_2.createBtn("pb8", "pb8", False)
        self.gridLayout_2.addWidget(self.widget_2.pb8_btn, 2, 0, 1, 1)
        self.widget_2.createBtn("pb9", "pb9", False)
        self.gridLayout_2.addWidget(self.widget_2.pb9_btn, 14, 0, 1, 1)
        self.widget_2.createBtn("pb10", "pb10", False)
        self.gridLayout_2.addWidget(self.widget_2.pb10_btn, 7, 1, 1, 1)
        self.widget_2.createBtn("pb11", "pb11", False)
        self.gridLayout_2.addWidget(self.widget_2.pb11_btn, 12, 0, 1, 1)
        self.widget_2.createBtn("pb12", "pb12", False)
        self.gridLayout_2.addWidget(self.widget_2.pb12_btn, 3, 0, 1, 1)
        self.widget_2.createBtn("pb13", "pb13", False)
        self.gridLayout_2.addWidget(self.widget_2.pb13_btn, 2, 2, 1, 1)
        self.widget_2.createBtn("pb14", "pb14", False)
        self.gridLayout_2.addWidget(self.widget_2.pb14_btn, 14, 2, 1, 1)
        self.widget_2.createBtn("pb15", "pb15", False)
        self.gridLayout_2.addWidget(self.widget_2.pb15_btn, 10, 0, 1, 1)
        self.widget_2.createBtn("pb16", "pb16", False)
        self.gridLayout_2.addWidget(self.widget_2.pb16_btn, 8, 0, 1, 1)
        self.widget_2.createBtn("pb17", "pb17", False)
        self.gridLayout_2.addWidget(self.widget_2.pb17_btn, 8, 2, 1, 1)
        self.widget_2.createBtn("pb18", "pb18", False)
        self.gridLayout_2.addWidget(self.widget_2.pb18_btn, 13, 1, 1, 1)
        self.widget_2.createBtn("pb19", "pb19", False)
        self.gridLayout_2.addWidget(self.widget_2.pb19_btn, 15, 1, 1, 1)
        self.widget_2.createBtn("pb20", "pb20", False)
        self.gridLayout_2.addWidget(self.widget_2.pb20_btn, 3, 2, 1, 1)
        self.widget_2.createBtn("pb21", "pb21", False)
        self.gridLayout_2.addWidget(self.widget_2.pb21_btn, 6, 0, 1, 1)
        self.widget_2.createBtn("pb22", "pb22", False)
        self.gridLayout_2.addWidget(self.widget_2.pb22_btn, 11, 1, 1, 1)
        self.widget_2.createBtn("pb23", "pb23", False)
        self.gridLayout_2.addWidget(self.widget_2.pb23_btn, 3, 1, 1, 1)
        self.widget_2.createBtn("pb24", "pb24", False)
        self.gridLayout_2.addWidget(self.widget_2.pb24_btn, 6, 2, 1, 1)
        self.widget_2.createBtn("pb25", "pb25", False)
        self.gridLayout_2.addWidget(self.widget_2.pb25_btn, 12, 2, 1, 1)
        self.widget_2.createBtn("pb26", "pb26", False)
        self.gridLayout_2.addWidget(self.widget_2.pb26_btn, 16, 0, 1, 1)
        self.widget_2.createBtn("pb27", "pb27", False)
        self.gridLayout_2.addWidget(self.widget_2.pb27_btn, 16, 2, 1, 1)
        self.widget_2.createBtn("pb28", "pb28", False)
        self.gridLayout_2.addWidget(self.widget_2.pb28_btn, 17, 1, 1, 1)
        self.widget_2.createBtn("pb29", "pb29", False)
        self.gridLayout_2.addWidget(self.widget_2.pb29_btn, 18, 1, 1, 1)
        self.widget_2.createBtn("pb30", "pb30", False)
        self.gridLayout_2.addWidget(self.widget_2.pb30_btn, 19, 1, 1, 1)
        self.widget_2.createBtn("pb31", "pb31", False)
        self.gridLayout_2.addWidget(self.widget_2.pb31_btn, 20, 1, 1, 1)
        self.widget_2.createBtn("pb32", "pb32", False)
        self.gridLayout_2.addWidget(self.widget_2.pb32_btn, 21, 1, 1, 1)
        self.widget_2.createBtn("pb33", "pb33", False)
        self.gridLayout_2.addWidget(self.widget_2.pb33_btn, 22, 1, 1, 1)
        self.widget_2.createBtn("pb34", "pb34", False)
        self.gridLayout_2.addWidget(self.widget_2.pb34_btn, 23, 1, 1, 1)
        self.widget_2.createBtn("pb35", "pb35", False)
        self.gridLayout_2.addWidget(self.widget_2.pb35_btn, 24, 1, 1, 1)

        self.gridLayout.addWidget(self.widget_2, 1, 0, 1, 1)
        self.widget = appCore.widgetClass(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.widget, 1, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.formLayout.setWidget(0, QFormLayout.SpanningRole, self.scrollArea)
        self.setCentralWidget(self.centralwidget)

        """self.scrollWidgetContents = appCore.widgetClass()
        self.scrollObj = QScrollArea()
        self.layoutObj = QVBoxLayout()

        self.createBtn(name = "node_1", text = "Logout")
        self.layoutObj.addWidget(self.node_1_btn)
        self.scrollWidgetContents.setLayout(self.layoutObj)

        self.scrollObj.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.scrollObj.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scrollObj.setWidgetResizable(True)
        self.scrollObj.setWidget(self.scrollWidgetContents)
        self.scrollObj.setGeometry(QRect(0, 0, 1920, 1080))

        self.setCentralWidget(self.scrollObj)"""

    def resetWindow(self):
        pass